# Site/SEO settings
email: hi@dergigi.com
baseurl: ""
paginate: 99
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics:

name: Gigi
title: SecretSatsa.com
description: >
  Spread Sats and Love alike!
url: https://secretsatsa.com
twitter_username: dergigi
default_img: /assets/images/twitter.png
social:
  - name: twitter
    url: https://twitter.com/dergigi
  - name: github
    url: https://github.com/secretsatsa/secretsatsa.github.io
  - name: bitcoin
    url: https://dergigi.com/support

# Collections
collections_dir: collections
collections:
  items:
    title: Items
  shops:
    title: Shops

# Author settings
author:
  - name: Gigi
    bio: Writing words and code for Bitcoin.
    url: https://dergigi.com/contact

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - env
  - scripts
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
